### PR TITLE
update jssm-viz version

### PR DESCRIPTION
**Pull request by machinshin**

### CODE REVIEW

**Comment by StoneCypher** [comment]
This needs a package.json version number bump so it can be republished too

**Comment by StoneCypher** [comment]
And it needs to be rebuilt after the package bump because the version number is part of the build

**Comment by machinshin** [comment]
@StoneCypher : i'm assuming a minor version change to 1.17.5?

**Comment by StoneCypher** [comment]
ya prolly

**Comment by StoneCypher** [comment]
I don't understand why this isn't running the action

**Comment by StoneCypher** [comment]
ok, replacing the action file fixed it, probably an old notation failed a month ago

gross

**Comment by StoneCypher** [comment]
could i get you to merge master again so it'll run the action?  sorry

**Pull request merged**
